### ISSUE TITLE
This works perfectly on google colab but on windows this error comes up

### ISSUE THREAD

**Issue by ankitgurua** [MahmoudAshraf97/ctc-forced-aligner#10]
```
FutureWarning: resume_download is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use force_download=True. 
  warnings.warn( 
Some weights of the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_g', 'wav2vec2.encoder.pos_conv_embed.conv.weight_v'] 
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model). 
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model). 
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1'] 
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference. 
C:\Program Files\Python310\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: resume_download is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use force_download=True. 
  warnings.warn( 
C:\Program Files\Python310\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.) 
  return F.conv1d(input, weight, bias, self.stride, 
Traceback (most recent call last): 
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in runmodule_as_main 
    return runcode(code, main_globals, None, 
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in runcode 
    exec(code, run_globals) 
  File "C:\Program Files\Python310\Scripts\ctc-forced-aligner.exe\main.py", line 7, in <module> 
  File "C:\Program Files\Python310\lib\site-packages\ctc_forced_aligner\align.py", line 147, in cli 
    tokens_starred, text_starred = preprocess_text( 
  File "C:\Program Files\Python310\lib\site-packages\ctc_forced_aligner\text_utils.py", line 214, in preprocess_text 
    tokens = get_uroman_tokens(norm_text, language) 
  File "C:\Program Files\Python310\lib\site-packages\ctc_forced_aligner\text_utils.py", line 165, in get_uroman_tokens 
    subprocess.run(cmd, check=True, stdin=tf1, stdout=tf2) 
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run 
    with Popen(*popenargs, kwargs) as process: 
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in init** 
    self._execute_child(args, executable, preexec_fn, close_fds, 
  File "C:\Program Files\Python310\lib\subprocess.py", line 1456, in executechild 
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args, 
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ankitgurua** [comment]
C'mon dude i really like this, please help me. 

I use this alot on my colab really wanna work with windows as well

**Comment by MahmoudAshraf97** [comment]
Make sure you have a valid perl installation
To verify, type perl into the cmd and see if it works

**Comment by ankitgurua** [comment]
What's up with cudnn error?

**Comment by MahmoudAshraf97** [comment]
Just a warning, ignore it
