### ISSUE TITLE
AssertionError: uroman not found

### ISSUE THREAD

**Issue by yuanquderzi** [MahmoudAshraf97/ctc-forced-aligner#15]
```Traceback (most recent call last):
  File "/workspace/diarize.py", line 145, in <module>
    tokens_starred, text_starred = preprocess_text(
  File "/usr/local/lib/python3.10/site-packages/ctc_forced_aligner-0.2-py3.10-linux-x86_64.egg/ctc_forced_aligner/text_utils.py", line 214, in preprocess_text
    tokens = get_uroman_tokens(norm_text, language)
  File "/usr/local/lib/python3.10/site-packages/ctc_forced_aligner-0.2-py3.10-linux-x86_64.egg/ctc_forced_aligner/text_utils.py", line 157, in get_uroman_tokens
    assert os.path.exists(
AssertionError: uroman not found```

**Comment by yuanquderzi** [comment]
Which package should be reinstalled?

**Comment by yuanquderzi** [comment]
> can you try installing again and use `--force-reinstall` option?

Which package should be reinstalled?

**Comment by MahmoudAshraf97** [comment]
```
pip install git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git --force-reinstall
```

**Comment by yuanquderzi** [comment]
> ```
> pip install git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git --force-reinstall
> ```

Thank you, the method you provided is feasible！！！！！！！
