### ISSUE TITLE
AssertionError using custom model from README

### ISSUE THREAD

**Issue by rehandaphedar** [MahmoudAshraf97/ctc-forced-aligner#16]
Main error message:
```
Traceback (most recent call last):
  File "/tmp/ctc-forced-aligner/venv/bin/ctc-forced-aligner", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/tmp/ctc-forced-aligner/venv/lib/python3.12/site-packages/ctc_forced_aligner/align.py", line 157, in cli
    spans = get_spans(tokens_starred, segments, tokenizer.decode(blank_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ctc-forced-aligner/venv/lib/python3.12/site-packages/ctc_forced_aligner/alignment_utils.py", line 63, in get_spans
    assert seg.label == ltr, f"{seg.label} != {ltr}"
           ^^^^^^^^^^^^^^^^
AssertionError: ن != ٰ
```
Reproduction:
```bash
mkdir -p /tmp/ctc-forced-aligner
cd /tmp/ctc-forced-aligner
python -m venv venv
venv/bin/pip install git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git
ffmpeg -i https://everyayah.com/data/Abu_Bakr_Ash-Shaatree_128kbps/001001.mp3 audio.wav
wget https://github.com/user-attachments/files/16926847/text.txt
venv/bin/ctc-forced-aligner --audio_path "audio.wav" --text_path "text.txt" --language "ara" --alignment_model "jonatasgrosman/wav2vec2-large-xlsr-53-arabic"
```
On python v3.12.5

The `text.txt` used, as well as the complete log are attached. GitHub doesn't support attaching `.wav` files. The `audio.wav` can be obtained like this (If it fails you can download from the link and convert manually):
```bash
ffmpeg -i https://everyayah.com/data/Abu_Bakr_Ash-Shaatree_128kbps/001001.mp3 audio.wav
``` 

[text.txt](https://github.com/user-attachments/files/16926847/text.txt)
[log.txt](https://github.com/user-attachments/files/16926845/log.txt)

**Comment by MahmoudAshraf97** [comment]
Should be solved now
