### ISSUE TITLE
ctc-forced-aligner breaks for 0 batch size

### ISSUE THREAD

**Issue by SIlver--** [MahmoudAshraf97/ctc-forced-aligner#21]
When trying to do batch-size 0, ctc-forced-aligner throws error.

```
  Traceback (most recent call last):
    File "/app/whisper-diarization/diarize.py", line 139, in <module>
      emissions, stride = generate_emissions(
    File "/usr/local/lib/python3.10/site-packages/ctc_forced_aligner/alignment_utils.py", line 134, in generate_emissions
      for i in range(0, input_tensor.size(0), batch_size):
  ValueError: range() arg 3 must not be zero
```

**Comment by MahmoudAshraf97** [comment]
fixed in the latest commit, please reinstall `ctc-forced-aligner` and pull the latest version of `whisper-diarize`
