### ISSUE TITLE
"No module named 'torch'" although torch is installed.

### ISSUE THREAD

**Issue by fsteckel** [MahmoudAshraf97/ctc-forced-aligner#3]
Hello.

When installing, I run into the following error. I created a venv and installed pytorch in the venv. torch is importable:

`(base) user@machine:path# ./venv/bin/python`
```
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> exit()
```
However, when I use this venv to install the library, It says that ther is no module named torch:
`(base) user@machine:path# ./venv/bin/python -m pip install git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git`
```
Collecting git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git
  Cloning https://github.com/MahmoudAshraf97/ctc-forced-aligner.git to /tmp/pip-req-build-k6h1s_d9
  Running command git clone --filter=blob:none --quiet https://github.com/MahmoudAshraf97/ctc-forced-aligner.git /tmp/pip-req-build-k6h1s_d9
  Resolved https://github.com/MahmoudAshraf97/ctc-forced-aligner.git to commit 6d4a4489b8c79e01450678c6b6d6f7bb3d2a14ac
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "path/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "path/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "path/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_yq69_f7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_yq69_f7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-_yq69_f7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-_yq69_f7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

How can I circumvent this issue? Machine is a WSL running Ubuntu 22.04.4 LTS. Python is 3.11.4

**Comment by MahmoudAshraf97** [comment]
Hello, I just tried the same steps on my end but using python 3.10 and couldn't reproduce it unfortunately, can you reinstall torch? or maybe start with a new env? this is my pip freeze for a new env
```
ctcenv2/sourcecreated virtual environment CPython3.10.12.final.0-64 in 6390ms
  creator CPython3Posix(dest=/mnt/e/***/ctcenv2, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mahmoud/.local/share/virtualenv)
    added seed packages: pip==24.0, setuptools==69.5.1, wheel==0.43.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
```
```
Package                  Version
------------------------ ----------
filelock                 3.14.0
fsspec                   2024.5.0
Jinja2                   3.1.4
MarkupSafe               2.1.5
mpmath                   1.3.0
networkx                 3.3
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.40
nvidia-nvtx-cu12         12.1.105
pip                      24.0
setuptools               69.5.1
sympy                    1.12
torch                    2.3.0
triton                   2.3.0
typing_extensions        4.11.0
wheel                    0.43.0
```

**Comment by buddhagurung** [comment]
I had the same issue. Saw in another forum that wheel was missing. pip install wheel and the issue was gone!
@MahmoudAshraf97 btw, love the work!

**Comment by fsteckel** [comment]
> I had the same issue. Saw in another forum that wheel was missing. pip install wheel and the issue was gone! @MahmoudAshraf97 btw, love the work!

Thanks a million, this was it. 
@MahmoudAshraf97 I agree, great work. Maybe add the wheel package to the requirements.
Issue is closed
