### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by andriken** [MahmoudAshraf97/ctc-forced-aligner#31]
I was running the python usage code, same as it is except the filenames were changed, and got below error

```
(D:\ctc\ctcenv) PS D:\ctc> python runy.py
Traceback (most recent call last):
  File "D:\ctc\runy.py", line 35, in <module>
    tokens_starred, text_starred = preprocess_text(
  File "C:\Users\Andriken\AppData\Roaming\Python\Python310\site-packages\ctc_forced_aligner\text_utils.py", line 220, in preprocess_text
    tokens = get_uroman_tokens(norm_text, language)
  File "C:\Users\Andriken\AppData\Roaming\Python\Python310\site-packages\ctc_forced_aligner\text_utils.py", line 153, in get_uroman_tokens
    assert not subprocess.call(
  File "C:\Program Files\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by MahmoudAshraf97** [comment]
You need to have a valid `perl` installation

**Comment by andriken** [comment]
I downloaded strawberry version of perl and then ran the code again and it works now Thanks for you quick response.
